import { Casino, NavigationItem } from './types';

export const navigationItems: NavigationItem[] = [
  { label: 'Home', href: '/' },
  { label: 'Casino Info', href: '/casinos' },
  { label: 'Reviews', href: '/reviews' },
  { label: 'Guides', href: '/guides' },
];

// Helper function to generate a random rating
const getRandomRating = () => {
  return parseFloat((Math.random() * (4.9 - 4.4) + 4.4).toFixed(1));
};

export const mockCasinos: Casino[] = [
  {
    id: 'crowncoins',
    name: 'Crowncoins',
    slug: 'crowncoins',
    logoUrl: '/images/casinos/crowncoins.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '1 SC Daily',
      description: 'Top tier, great daily reward. Extra freebie links daily. Tons of games, fun promos.',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Top tier casino', 'Great daily rewards', 'Extra freebie links', 'Huge game selection'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '1',
        author: 'Admin',
        rating: 5,
        comment: 'Huge value overall - CrownCoins is my personal favorite.',
        date: '2024-03-15',
      },
    ],
    bestGames: [
      { name: 'Sugar Rush', rtp: '96.50%' },
      { name: 'Gates of Olympus', rtp: '96.50%' },
    ],
  },
  {
    id: 'realprize',
    name: 'RealPrize',
    slug: 'realprize',
    logoUrl: '/images/casinos/realprize.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.3 SC Daily',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '2',
        author: 'Admin',
        rating: 5,
        comment: 'Don\'t skip RealPrize',
        date: '2024-03-15',
      },
    ],
    bestGames: [
      { name: 'Big Bass Bonanza', rtp: '96.71%' },
      { name: 'Sweet Bonanza', rtp: '96.48%' },
    ],
  },
  {
    id: 'pulsz',
    name: 'Pulsz',
    slug: 'pulsz',
    logoUrl: '/images/casinos/pulsz.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '1 SC Daily with streak',
      description: 'Great welcome offers, 10–20% daily sales, great multi-hand blackjack game',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily sales', 'Multi-hand blackjack', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Blackjack'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '3',
        author: 'Admin',
        rating: 5,
        comment: 'One of my favorites to start with',
        date: '2024-03-15',
      },
    ],
    bestGames: [
      { name: 'Wolf Gold', rtp: '96.01%' },
      { name: 'The Dog House Megaways', rtp: '96.55%' },
    ],
  },
  {
    id: 'wow-vegas',
    name: 'WOW Vegas',
    slug: 'wow-vegas',
    logoUrl: '/images/casinos/wow-vegas.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.3-1+ SC Daily with VIP',
      description: 'Great welcome offers and daily Happy Hour sale. Free spins given away daily',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily Happy Hour', 'Free spins', 'Free SC links'],
    cons: ['Recent nerfs', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '4',
        author: 'Admin',
        rating: 5,
        comment: 'A few nerfs lately, but WowVegas is still a top tier platform.',
        date: '2024-03-15',
      },
    ],
    bestGames: [
      { name: 'Wild Wild Riches', rtp: '96.77%' },
      { name: 'Mustang Gold', rtp: '96.53%' },
    ],
  },
  {
    id: 'casino-click',
    name: 'Casino Click',
    slug: 'casino-click',
    logoUrl: '/images/casinos/casino-click.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '10 Free Spins Daily',
      description: 'Insane daily free spins! Huge sales, and a ton of games.',
    },
    features: ['Daily Rewards', 'Cash Redemption', 'Gift Card Redemption', 'Crypto Redemption'],
    pros: ['Daily free spins', 'Huge sales', 'Large game selection', 'Multiple redemption options'],
    cons: ['No VIP system'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards', 'Crypto'],
    reviews: [
      {
        id: '5',
        author: 'Admin',
        rating: 5,
        comment: 'The group has been loving Click!',
        date: '2024-03-15',
      },
    ],
    bestGames: [
      { name: 'John Hunter and the Book of Tut', rtp: '96.50%' },
      { name: 'Fruit Party', rtp: '96.47%' },
    ],
  },
  {
    id: 'high5',
    name: 'High5',
    slug: 'high5',
    logoUrl: '/images/casinos/high5.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.5 SC Daily',
      description: 'Regular sales up to 20%, can get 1005SC for $800',
    },
    features: ['Daily Rewards', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Regular sales', 'Good value', 'High 5 Plinko', 'Fast redemptions'],
    cons: ['No VIP system', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Plinko'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '6',
        author: 'Admin',
        rating: 4,
        comment: 'High 5 Plinko is top tier to wash with',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'modo',
    name: 'Modo',
    slug: 'modo',
    logoUrl: '/images/casinos/modo.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '1 SC Daily after streak',
      description: 'Excellent casino, quick redemptions. Great selection of games.',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Quick redemptions', 'Great game selection', 'Good welcome offers', 'Great reputation'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '7',
        author: 'Admin',
        rating: 5,
        comment: 'Great reputation',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'stake',
    name: 'Stake',
    slug: 'stake',
    logoUrl: '/images/casinos/stake.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '1 SC Daily',
      description: 'No playthrough requirement on daily SC. Just farm and redeem.',
    },
    features: ['Daily Rewards', 'VIP Program', 'Crypto Redemption'],
    pros: ['No playthrough requirement', 'Easy farming', 'Fast redemptions', 'Crypto support'],
    cons: ['No cash redemption', 'No gift card redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Crypto'],
    reviews: [
      {
        id: '8',
        author: 'Admin',
        rating: 5,
        comment: 'Don\'t skip this one, it is literally free money',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'jackpota',
    name: 'Jackpota',
    slug: 'jackpota',
    logoUrl: '/images/casinos/jackpota.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.25 to 0.5 SC Daily random',
      description: 'My favorite McLuck clone. Huge sales, great selection of games.',
    },
    features: ['Daily Rewards', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Huge sales', 'Great game selection', 'Weekly freebies', 'Fast redemptions'],
    cons: ['No VIP system', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '9',
        author: 'Admin',
        rating: 5,
        comment: 'Expect fast redemptions here as well.',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'zula',
    name: 'Zula',
    slug: 'zula',
    logoUrl: '/images/casinos/zula.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.5 to 1.5 SC Daily random',
      description: 'Overall great casino, generous daily, lots of freebies, and great sales',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption'],
    pros: ['Generous daily rewards', 'Lots of freebies', 'Great sales', 'Good reputation'],
    cons: ['No gift card redemption', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash'],
    reviews: [
      {
        id: '10',
        author: 'Admin',
        rating: 4,
        comment: 'Overall great casino',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'mcluck',
    name: 'McLuck',
    slug: 'mcluck',
    logoUrl: '/images/casinos/mcluck.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.25 to 0.5 SC Daily random',
      description: 'My favorite McLuck clone. Huge sales, great selection of games.',
    },
    features: ['Daily Rewards', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Huge sales', 'Great game selection', 'Weekly freebies', 'Fast redemptions'],
    cons: ['No VIP system', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '11',
        author: 'Admin',
        rating: 5,
        comment: 'Expect fast redemptions here as well.',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'sweepslots',
    name: 'Sweepslots',
    slug: 'sweepslots',
    logoUrl: '/images/casinos/sweepslots.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.3 SC Daily',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '12',
        author: 'Admin',
        rating: 5,
        comment: 'Don\'t skip Sweepslots',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'moonspin',
    name: 'Moonspin',
    slug: 'moonspin',
    logoUrl: '/images/casinos/moonspin.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.3-1+ SC Daily with VIP',
      description: 'Great welcome offers and daily Happy Hour sale. Free spins given away daily',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily Happy Hour', 'Free spins', 'Free SC links'],
    cons: ['Recent nerfs', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '13',
        author: 'Admin',
        rating: 5,
        comment: 'A few nerfs lately, but Moonspin is still a top tier platform.',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'chanced',
    name: 'Chanced',
    slug: 'chanced',
    logoUrl: '/images/casinos/chanced.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.3 SC Daily',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '14',
        author: 'Admin',
        rating: 5,
        comment: 'Don\'t skip Chanced',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'luckyland',
    name: 'LuckyLand Slots',
    slug: 'luckyland',
    logoUrl: '/images/casinos/luckyland.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.3 SC Daily',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '15',
        author: 'Admin',
        rating: 5,
        comment: 'Don\'t skip LuckyLand',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'chumbacasino',
    name: 'Chumba Casino',
    slug: 'chumbacasino',
    logoUrl: '/images/casinos/chumba.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.3 SC Daily',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '16',
        author: 'Admin',
        rating: 5,
        comment: 'Don\'t skip Chumba',
        date: '2024-03-15',
      },
    ],
  },
  {
    id: 'globalpoker',
    name: 'Global Poker',
    slug: 'globalpoker',
    logoUrl: '/images/casinos/globalpoker.png',
    rating: getRandomRating(),
    welcomeBonus: {
      amount: '0.3 SC Daily',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '17',
        author: 'Admin',
        rating: 5,
        comment: 'Don\'t skip Global Poker',
        date: '2024-03-15',
      },
    ],
  }
]; 