import { Casino, NavigationItem } from './types';

export const navigationItems: NavigationItem[] = [
  { label: 'Home', href: '/' },
  { label: 'Casino Info', href: '/casinos' },
  { label: 'Guides', href: '/guides' },
  { label: 'Free SC and Sales', href: '/discord-sales' },
  { label: 'Leaderboard', href: '/leaderboard' },
];

export const mockCasinos: Casino[] = [
  {
    id: 'crowncoins',
    name: 'CrownCoinsCasino',
    slug: 'crowncoins',
    logoUrl: '/images/casinos/ccc.jpg',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: 'Streak with Wheel',
      description: 'Top tier, great daily reward. Extra freebie links daily. Tons of games, fun promos.',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Top tier casino', 'Great daily rewards', 'Extra freebie links', 'Huge game selection'],
    cons: ['No crypto redmption'],
    games: ['Slots'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '1',
        author: 'Admin',
        rating: 5,
        comment: 'Huge value overall - CrownCoins is my personal favorite.',
        date: '2024-03-15',
      },
    ],
    bestGames: ["Money Roll"],
    dailyMinSc: 0,
    dailyMaxSc: 0.8
  },
  {
    id: 'realprize',
    name: 'RealPrize',
    slug: 'realprize',
    logoUrl: '/images/casinos/realprize.jpg',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: '0.3 SC Daily and $55 for $25 bonus',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '2',
        author: 'Admin',
        rating: 5,
        comment: "Don't skip RealPrize",
        date: '2024-03-15',
      },
    ],
    bestGames: ["Joker's Jewels"],
    dailyMinSc: 0.3,
    dailyMaxSc: 0.3
  },
  {
    id: 'pulsz',
    name: 'Pulsz',
    slug: 'pulsz',
    logoUrl: '/images/casinos/pulsz.jpg',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: 'Streak bonus and great offers',
      description: 'Great welcome offers, 10–20% daily sales, great multi-hand blackjack game',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily sales', 'Multi-hand blackjack', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Blackjack'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '3',
        author: 'Admin',
        rating: 5,
        comment: 'One of my favorites to start with',
        date: '2024-03-15',
      },
    ],
    bestGames: [
      "Dice", "Multi-hand blackjack",
    ],
    dailyMinSc: 1,
    dailyMaxSc: 1
  },
  {
    id: 'pulszbingo',
    name: 'Pulszbingo',
    slug: 'pulszbingo',
    logoUrl: '/images/casinos/pulszbingo.jpg',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: 'Wheel Daily with streak',
      description: 'Great welcome offers, 10–20% daily sales, great multi-hand blackjack game',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily sales', 'Multi-hand blackjack', 'Fast redemptions'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Blackjack', 'Bingo'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: 'pulszbingo-review-admin',
        author: 'Admin',
        rating: 5,
        comment: 'One of my favorites to start with, now with Bingo!',
        date: '2024-07-26',
      },
    ],
    bestGames: ["Bingo", "Multi-hand blackjack"],
    dailyMinSc: 0.1,
    dailyMaxSc: 20
  },
  {
    id: 'wowvegas',
    name: 'Wowvegas',
    slug: 'wowvegas',
    logoUrl: '/images/casinos/wowvegas.jpg',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: '0.3-1+ SC Daily with VIP',
      description: 'Great welcome offers and daily Happy Hour sale. Free spins given away daily',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily Happy Hour', 'Free spins', 'Free SC links'],
    cons: ['Recent nerfs', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: 'wowvegas-review-admin',
        author: 'Admin',
        rating: 5,
        comment: 'A few nerfs lately, but WowVegas is still a top tier platform.',
        date: '2024-07-26',
      },
    ],
    bestGames: [
      "Joker's Jewels",
    ],
    dailyMinSc: 0,
    dailyMaxSc: 1
  },
  {
    id: 'casinoclick',
    name: 'Casinoclick',
    slug: 'casinoclick',
    logoUrl: '/images/casinos/casinoclick.jpeg',
    tier: 'Great',
    welcomeBonus: {
      amount: 'Wheel Daily',
      description: 'Insane daily free spins! Huge sales, and a ton of games.',
    },
    features: ['Daily Rewards', 'Cash Redemption', 'Gift Card Redemption', 'Crypto Redemption'],
    pros: ['Daily free spins', 'Huge sales', 'Large game selection', 'Multiple redemption options'],
    cons: ['No VIP system'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards', 'Crypto'],
    reviews: [
      {
        id: 'casinoclick-review-admin',
        author: 'Admin',
        rating: 5,
        comment: 'The group has been loving Click!',
        date: '2024-07-26',
      },
    ],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0,
    dailyMaxSc: 5
  },
  {
    id: 'modo',
    name: 'Modo',
    slug: 'modo',
    logoUrl: '/images/casinos/modo.png',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: 'streak',
      description: 'Excellent casino, quick redemptions. Great selection of games.',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Quick redemptions', 'Great game selection', 'Good welcome offers', 'Great reputation'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '7',
        author: 'Admin',
        rating: 5,
        comment: 'Great reputation',
        date: '2024-03-15',
      },
    ],
    bestGames: ["Joker's Jewels", "Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0.3,
    dailyMaxSc: 5
  },
  {
    id: 'jackpota',
    name: 'Jackpota',
    slug: 'jackpota',
    logoUrl: '/images/casinos/jackpota.jpg',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: '0.25 to 0.5 SC Daily random',
      description: 'My favorite clone. Huge sales, great selection of games.',
    },
    features: ['Daily Rewards', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Huge sales', 'Great game selection', 'Weekly freebies', 'Fast redemptions'],
    cons: ['No VIP system', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '9',
        author: 'Admin',
        rating: 5,
        comment: 'Expect fast redemptions here as well.',
        date: '2024-03-15',
      },
    ],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0.25,
    dailyMaxSc: 0.25
  },
  {
    id: 'zula',
    name: 'Zula',
    slug: 'zula',
    logoUrl: '/images/casinos/zula.jpeg',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: '0.5 to 1.5 SC Daily random',
      description: 'Overall great casino, generous daily, lots of freebies, and great sales',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption'],
    pros: ['Generous daily rewards', 'Lots of freebies', 'Great sales', 'Good reputation'],
    cons: ['No gift card redemption', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash'],
    reviews: [
      {
        id: '10',
        author: 'Admin',
        rating: 4,
        comment: 'Overall great casino',
        date: '2024-03-15',
      },
    ],
    bestGames: [""],
    dailyMinSc: 1,
    dailyMaxSc: 1
  },
  {
    id: 'sportsmillions',
    name: 'Sportsmillions',
    slug: 'sportsmillions',
    logoUrl: '/images/casinos/sportsmillions.jpg',
    tier: 'Fantastic',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Sports Themed', 'Unique Games'],
    pros: ['New Platform', 'Exciting Promotions'],
    cons: ['Details TBC'],
    games: ['Slots', 'Virtual Sports'],
    paymentMethods: ['Visa', 'Mastercard', 'Crypto (TBD)'],
    reviews: [{
        id: 'sportsmillions-review-admin',
        author: 'Admin',
        rating: 4.5,
        comment: 'Welcome Sportsmillions! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0.25,
    dailyMaxSc: 0.25
  },
  {
    id: 'hellomillions',
    name: 'Hellomillions',
    slug: 'hellomillions',
    logoUrl: '/images/casinos/hellomillions.jpg',
    tier: 'Fantastic',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Large Jackpots', 'User-Friendly'],
    pros: ['Generous Welcome Offer', 'Frequent Promotions'],
    cons: ['Details TBC'],
    games: ['Slots', 'Jackpot Games'],
    paymentMethods: ['Visa', 'Mastercard', 'Skrill'],
    reviews: [{
        id: 'hellomillions-review-admin',
        author: 'Admin',
        rating: 4.6,
        comment: 'Welcome Hellomillions! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0.2,
    dailyMaxSc: 0.4
  },
  {
    id: 'yaycasino',
    name: 'Yaycasino',
    slug: 'yaycasino',
    logoUrl: '/images/casinos/yaycasino.png',
    tier: 'Fantastic',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Fun Theme', 'Mobile Friendly'],
    pros: ['Unique Games', 'Engaging Experience'],
    cons: ['Details TBC'],
    games: ['Slots', 'Casual Games'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'yaycasino-review-admin',
        author: 'Admin',
        rating: 4.3,
        comment: 'Welcome Yaycasino! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Joker's Jewels"],
    dailyMinSc: 1,
    dailyMaxSc: 1
  },

  {
    id: 'high5',
    name: 'High5',
    slug: 'high5',
    logoUrl: '/images/casinos/high5.jpg',
    tier: 'Great',
    welcomeBonus: {
      amount: '0.1 SC Daily',
      description: 'Interesting diamond system',
    },
    features: ['Daily Rewards', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Regular sales', 'Good value', 'High 5', 'Fast redemptions'],
    cons: ['No VIP system', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Plinko'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '6',
        author: 'Admin',
        rating: 4,
        comment: 'High 5  is top tier to wash with',
        date: '2024-03-15',
      },
    ],
    bestGames: [""],
    dailyMinSc: 0.1,
    dailyMaxSc: 0.1
  },
  {
    id: 'themoneyfactory',
    name: 'Themoneyfactory',
    slug: 'themoneyfactory',
    logoUrl: '/images/casinos/themoneyfactory.png',
    tier: 'Great',
    welcomeBonus: { amount: 'decent bonuses and streak', description: 'Lots of bonuses and a good streak system.' },
    features: ['Daily Rewards', 'Bonus Wheel', 'VIP Program'],
    pros: ['Lots of Bonuses', 'Industrial Theme'],
    cons: ['Details to be confirmed'],
    games: ['Slots', 'Progressive Jackpots'],
    paymentMethods: ['Visa', 'Mastercard', 'PayPal'],
    reviews: [{
        id: 'themoneyfactory-review-admin',
        author: 'Admin',
        rating: 4.4,
        comment: 'Welcome Themoneyfactory! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Joker's Jewels"],
    dailyMinSc: .05,
    dailyMaxSc: 0.5
  },
  {
    id: 'fortunecoins',
    name: 'Fortunecoins',
    slug: 'fortunecoins',
    logoUrl: '/images/casinos/fortunecoins.jpg',
    tier: 'Great',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Fortune Wheel', 'Fish Games'],
    pros: ['Unique Game Types', 'Generous Coin System'],
    cons: ['Details TBC'],
    games: ['Slots', 'Fish Games', 'Keno'],
    paymentMethods: ['Visa', 'Mastercard', 'ACH'],
    reviews: [{
        id: 'fortunecoins-review-admin',
        author: 'Admin',
        rating: 4.7,
        comment: 'Welcome Fortunecoins! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: [""],
    dailyMinSc: 0.5,
    dailyMaxSc: 1.2
  },
  {
    id: 'spree',
    name: 'Spree',
    slug: 'spree',
    logoUrl: '/images/casinos/spree.jpg',
    tier: 'Solid',
    welcomeBonus: { amount: '2.5 SC', description: 'Kind buggy.' },
    features: ['Daily Rewards', 'Social Gaming', 'Tournaments'],
    pros: ['Modern Interface', 'Community Focus'],
    cons: ['Details TBC'],
    games: ['Slots', 'Live Casino (TBD)'],
    paymentMethods: ['Visa', 'Mastercard', 'Discover'],
    reviews: [{
        id: 'spree-review-admin',
        author: 'Admin',
        rating: 4.5,
        comment: 'Welcome Spree! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0,
    dailyMaxSc: 0
  },
  {
    id: 'sportzino',
    name: 'Sportzino',
    slug: 'sportzino',
    logoUrl: '/images/casinos/sportzino.jpg',
    tier: 'Great',
    welcomeBonus: { amount: 'Great streak', description: 'Details to be confirmed.' },
    features: ['Sportsbook (Social)', 'Casino Games', 'Daily Rewards'],
    pros: ['Sports & Casino Combo', 'Unique Offering'],
    cons: ['Details TBC'],
    games: ['Slots', 'Social Sports Betting'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'sportzino-review-admin',
        author: 'Admin',
        rating: 4.6,
        comment: 'Welcome Sportzino! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0.5,
    dailyMaxSc: 1.50
  },
  {
    id: 'legendz',
    name: 'Legendz',
    slug: 'legendz',
    logoUrl: '/images/casinos/legendz.jpeg',
    tier: 'Solid',
    welcomeBonus: { amount: 'stake clone', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Mythical Theme', 'Exclusive Games'],
    pros: ['Strong Theme', 'Engaging Storyline'],
    cons: ['Details TBC'],
    games: ['Slots', 'Adventure Games'],
    paymentMethods: ['Visa', 'Mastercard', 'Amex'],
    reviews: [{
        id: 'legendz-review-admin',
        author: 'Admin',
        rating: 4.4,
        comment: 'Welcome Legendz! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0,
    dailyMaxSc: 0
  },
  {
    id: 'mcluck',
    name: 'Mcluck',
    slug: 'mcluck',
    logoUrl: '/images/casinos/mcluck.png',
    tier: 'Great',
    welcomeBonus: {
      amount: '0.25 to 0.4 SC Daily random',
      description: 'My favorite McLuck. Huge sales, great selection of games.',
    },
    features: ['Daily Rewards', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Huge sales', 'Great game selection', 'Weekly freebies', 'Fast redemptions'],
    cons: ['No VIP system', 'No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '11',
        author: 'Admin',
        rating: 5,
        comment: 'Expect fast redemptions here as well.',
        date: '2024-03-15',
      },
    ],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0.2,
    dailyMaxSc: 0.4
  },
  {
    id: 'megabonanza',
    name: 'Megabonanza',
    slug: 'megabonanza',
    logoUrl: '/images/casinos/megabonanza.jpeg',
    tier: 'Great',
    welcomeBonus: { amount: 'consistent', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Huge Jackpots', 'Bonanza Games'],
    pros: ['Focus on Big Wins', 'Exciting Game Mechanics'],
    cons: ['Details TBC'],
    games: ['Slots', 'Megaways', 'Jackpot Slots'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'megabonanza-review-admin',
        author: 'Admin',
        rating: 4.5,
        comment: 'Welcome Megabonanza! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Mega Moolah Dreams", "Bonanza Blast Xtreme"],
    dailyMinSc: 0.25,
    dailyMaxSc: 0.25
  },
  {
    id: 'lonestar',
    name: 'Lonestar',
    slug: 'lonestar',
    logoUrl: '/images/casinos/lonestar.jpeg',
    tier: 'Solid',
    welcomeBonus: { amount: 'realprize clone .3', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Texas Theme', 'Poker (Social)'],
    pros: ['Regional Theme', 'Community Events'],
    cons: ['Details TBC'],
    games: ['Slots', 'Social Poker', 'Table Games'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'lonestar-review-admin',
        author: 'Admin',
        rating: 4.3,
        comment: 'Welcome Lonestar! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Joker's Jewels"],
    dailyMinSc: 0.3,
    dailyMaxSc: 0.3
  },
  {
    id: 'taofortune',
    name: 'Taofortune',
    slug: 'taofortune',
    logoUrl: '/images/casinos/taofortune.png',
    tier: 'Solid',
    welcomeBonus: { amount: 'Magic box and streak', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Asian Theme', 'Unique Slots'],
    pros: ['Calm Atmosphere', 'Cultural Theme'],
    cons: ['Details TBC'],
    games: ['Slots', 'Mahjong (Social)'],
    paymentMethods: ['Visa', 'Mastercard', 'UnionPay (TBD)'],
    reviews: [{
        id: 'taofortune-review-admin',
        author: 'Admin',
        rating: 4.6,
        comment: 'Welcome Taofortune! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: [""],
    dailyMinSc: 0,
    dailyMaxSc: 5
  },
  {
    id: 'rolla',
    name: 'Rolla',
    slug: 'rolla',
    logoUrl: '/images/casinos/rolla.jpg',
    tier: 'Great',
    welcomeBonus: { amount: 'New great daily', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Dice Games', 'Fast Paced'],
    pros: ['Quick Games', 'Simple Interface'],
    cons: ['Details TBC'],
    games: ['Slots', 'Dice', 'Crash Games (TBD)'],
    paymentMethods: ['Visa', 'Mastercard', 'Crypto'],
    reviews: [{
        id: 'rolla-review-admin',
        author: 'Admin',
        rating: 4.4,
        comment: 'Welcome Rolla! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 1,
    dailyMaxSc: 1
  },
  {
    id: 'nolimitcoins',
    name: 'Nolimitcoins',
    slug: 'nolimitcoins',
    logoUrl: '/images/casinos/nolimitcoins.jpg',
    tier: 'Solid',
    welcomeBonus: { amount: 'Streak great bonus free spins', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'High Stakes (Social)', 'Exclusive Slots'],
    pros: ['For High Rollers (Social)', 'Unique Nolimit City Slots (TBD)'],
    cons: ['Details TBC'],
    games: ['Slots', 'High Limit Slots'],
    paymentMethods: ['Visa', 'Mastercard', 'Bank Transfer'],
    reviews: [{
        id: 'nolimitcoins-review-admin',
        author: 'Admin',
        rating: 4.7,
        comment: 'Welcome Nolimitcoins! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: [""],
    dailyMinSc: 0.2,
    dailyMaxSc: .3
  },
  {
    id: 'spinblitz',
    name: 'Spinblitz',
    slug: 'spinblitz',
    logoUrl: '/images/casinos/spinblitz.jpg',
    tier: 'Great',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Fast Spins', 'Tournaments'],
    pros: ['Speedy Gameplay', 'Competitive Events'],
    cons: ['Details TBC'],
    games: ['Slots', 'Quick Spin Slots'],
    paymentMethods: ['Visa', 'Mastercard', 'eWallets'],
    reviews: [{
        id: 'spinblitz-review-admin',
        author: 'Admin',
        rating: 4.5,
        comment: 'Welcome Spinblitz! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Live Blackjack", "Live Roulette", "Live Bacarrat"],
    dailyMinSc: 0.2,
    dailyMaxSc: 0.35
    },
  {
    id: 'clubspoker',
    name: 'Clubspoker',
    slug: 'clubspoker',
    logoUrl: '/images/casinos/clubs.png',
    tier: 'Solid',
    welcomeBonus: { amount: 'Poker', description: 'Details to be confirmed.' },
    features: ['Social Poker', 'Private Clubs', 'Tournaments'],
    pros: ['Poker Community', 'Customizable Games'],
    cons: ['Primarily Poker'],
    games: ['Poker (Texas Hold\'em, Omaha)'],
    paymentMethods: ['In-App Purchases (TBD)'],
    reviews: [{
        id: 'clubspoker-review-admin',
        author: 'Admin',
        rating: 4.6,
        comment: 'Welcome Clubspoker! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Poker"],
    dailyMinSc: 0.2,
    dailyMaxSc: 0.2
  },
  {
    id: 'luckybird',
    name: 'Luckybird',
    slug: 'luckybird',
    logoUrl: '/images/casinos/luckybird.jpg',
    tier: 'Great',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Crypto Focused', 'Faucet'],
    pros: ['Crypto Options', 'Regular Free Coins'],
    cons: ['Details TBC'],
    games: ['Slots', 'Dice', 'Originals'],
    paymentMethods: ['Crypto (BTC, ETH, LTC)'],
    reviews: [{
        id: 'luckybird-review-admin',
        author: 'Admin',
        rating: 4.7,
        comment: 'Welcome Luckybird! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Crypto Crane Cash", "Faucet Fortune Slots"],
    dailyMinSc: 0.2,
    dailyMaxSc: 0.2
  },
  {
    id: 'fortunewheelz',
    name: 'Fortunewheelz',
    slug: 'fortunewheelz',
    logoUrl: '/images/casinos/fortunewheelz.jpeg',
    tier: 'Solid',
    welcomeBonus: { amount: 'daily wheel bonus and streak', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Prize Wheels', 'Interactive Games'],
    pros: ['Focus on Wheel Spins', 'Engaging Bonuses'],
    cons: ['Details TBC'],
    games: ['Slots', 'Wheel Games'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'fortunewheelz-review-admin',
        author: 'Admin',
        rating: 4.4,
        comment: 'Welcome Fortunewheelz! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Wheel of Wonders Win", "Spin & Score Slot"],
    dailyMinSc: 0.2,
    dailyMaxSc: 10
  },
  {
    id: 'chipnwin',
    name: 'Chipnwin',
    slug: 'chipnwin',
    logoUrl: '/images/casinos/chipnwin.jpg',
    tier: 'Solid',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Classic Casino Feel', 'Table Games Focus'],
    pros: ['Good for Table Game Fans', 'Simple Rewards'],
    cons: ['Details TBC'],
    games: ['Slots', 'Blackjack', 'Roulette'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'chipnwin-review-admin',
        author: 'Admin',
        rating: 4.3,
        comment: 'Welcome Chipnwin! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Classic Chip Collector", "Roulette Royale Supreme"],
    dailyMinSc: 0,
    dailyMaxSc: 0
  },
  {
    id: 'goldenheart',
    name: 'Goldenheart',
    slug: 'goldenheart',
    logoUrl: '/images/casinos/goldenheart.jpeg',
    tier: 'Solid',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Charity Focused', 'Bingo', 'Slots'],
    pros: ['Play for a Cause', 'Unique Model'],
    cons: ['Details TBC'],
    games: ['Slots', 'Bingo', 'Instant Win'],
    paymentMethods: ['Visa', 'Mastercard', 'PayPal'],
    reviews: [{
        id: 'goldenheart-review-admin',
        author: 'Admin',
        rating: 4.8,
        comment: 'Welcome Goldenheart! Play and support charities. More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Charity Bingo Bonanza", "Kindness Keno King"],
    dailyMinSc: 0.1,
    dailyMaxSc: 5
  },
  {
    id: 'jackpotrabbit',
    name: 'Jackpotrabbit',
    slug: 'jackpotrabbit',
    logoUrl: '/images/casinos/jackpotrabbit.png',
    tier: 'Solid',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Fun Theme', 'Progressive Jackpots'],
    pros: ['Cute Mascot', 'Focus on Jackpots'],
    cons: ['Details TBC'],
    games: ['Slots', 'Jackpot Slots'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'jackpotrabbit-review-admin',
        author: 'Admin',
        rating: 4.4,
        comment: 'Welcome Jackpotrabbit! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Lucky Carrot Loot", "Hoppin' Mad Jackpots"],
    dailyMinSc: 0.2,
    dailyMaxSc: 0.2
  },
  {
    id: 'spinsaga',
    name: 'Spinsaga',
    slug: 'spinsaga',
    logoUrl: '/images/casinos/spinsaga.jpg',
    tier: 'Unproven',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Adventure Theme', 'Gamified Experience'],
    pros: ['Story-driven', 'Quests and Rewards'],
    cons: ['Details TBC'],
    games: ['Slots', 'RPG-lite elements (TBD)'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'spinsaga-review-admin',
        author: 'Admin',
        rating: 4.5,
        comment: 'Welcome Spinsaga! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Adventure Isle Slots", "Quest for Coins RPG"],
    dailyMinSc: 0,
    dailyMaxSc: 0
  },
  {
    id: 'sixty6',
    name: 'Sixty6',
    slug: 'sixty6',
    logoUrl: '/images/casinos/sixty6.png',
    tier: 'Unproven',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Modern Design', 'Unique Games'],
    pros: ['Sleek Interface', 'Exclusive Titles (TBD)'],
    cons: ['Details TBC'],
    games: ['Slots', 'Originals'],
    paymentMethods: ['Visa', 'Mastercard', 'Crypto'],
    reviews: [{
        id: 'sixty6-review-admin',
        author: 'Admin',
        rating: 4.6,
        comment: 'Welcome Sixty6! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Route 66 Riches", "Neon Nights Slots"],
    dailyMinSc: 0.2,
    dailyMaxSc: 0.2
  },
  {
    id: 'globalpoker',
    name: 'Globalpoker',
    slug: 'globalpoker',
    logoUrl: '/images/casinos/globalpoker.jpg',
    tier: 'Solid',
    welcomeBonus: {
      amount: '0.3 SC Daily',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption', 'Poker'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions', 'Actual Poker'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer', 'Poker'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '17',
        author: 'Admin',
        rating: 5,
        comment: "Don't skip Global Poker",
        date: '2024-03-15',
      },
    ],
    bestGames: ["Global Poker Tourney (Social)", "Omaha Odds Player"],
    dailyMinSc: 0,
    dailyMaxSc: 0
  },
  {
    id: 'playfame',
    name: 'Playfame',
    slug: 'playfame',
    logoUrl: '/images/casinos/playfame.png',
    tier: 'Fantastic',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Celebrity Theme (TBD)', 'Interactive Events'],
    pros: ['Unique Concept', 'Social Integration'],
    cons: ['Details TBC'],
    games: ['Slots', 'Skill Games (TBD)'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'playfame-review-admin',
        author: 'Admin',
        rating: 4.4,
        comment: 'Welcome Playfame! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Red Carpet Reels", "Celebrity Challenge Slots"],
    dailyMinSc: 0,
    dailyMaxSc: 0
  },
  {
    id: 'funzcity',
    name: 'Funzcity',
    slug: 'funzcity',
    logoUrl: '/images/casinos/funzcity.jpg',
    tier: 'Solid',
    welcomeBonus: { amount: 'Broken site for myself', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'City Theme', 'Mini Games'],
    pros: ['Engaging World', 'Variety of Small Games'],
    cons: ['Details TBC'],
    games: ['Slots', 'Arcade-style Games'],
    paymentMethods: ['Visa', 'Mastercard', 'PayPal'],
    reviews: [{
        id: 'funzcity-review-admin',
        author: 'Admin',
        rating: 4.3,
        comment: 'Welcome Funzcity! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Arcade Adventure Slots", "Mini Game Mania Wins"],
    dailyMinSc: 0,
    dailyMaxSc: 0
  },
  {
    id: 'stakeus',
    name: 'Stake',
    slug: 'stakeus',
    logoUrl: '/images/casinos/stake.jpg',
    tier: 'Fantastic',
    welcomeBonus: {
      amount: '1 SC Daily',
      description: 'No playthrough requirement on daily SC. Just farm and redeem.',
    },
    features: ['Daily Rewards', 'VIP Program', 'Crypto Redemption'],
    pros: ['No playthrough requirement', 'Easy farming', 'Fast redemptions', 'Crypto support'],
    cons: ['No cash redemption', 'No gift card redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer'],
    paymentMethods: ['Crypto'],
    reviews: [
      {
        id: '8',
        author: 'Admin',
        rating: 5,
        comment: "Don't skip this one, it is literally free money",
        date: '2024-03-15',
      },
    ],
    bestGames: [
      "Gates of Olympus - High Volatility, 96.5% RTP",
      "Sweet Bonanza - Tumbling Reels, 96.48% RTP",
      "Wanted Dead or a Wild - Sticky Wilds, 96.38% RTP",
      "Sugar Rush - Cluster Pays, 96.50% RTP",
    ],
    dailyMinSc: 1,
    dailyMaxSc: 1
  },
  {
    id: 'moozi',
    name: 'Moozi',
    slug: 'moozi',
    logoUrl: '/images/casinos/moozi.png',
    tier: 'Solid',
    welcomeBonus: { amount: 'TBD', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Farm Theme', 'Unique Slots'],
    pros: ['Relaxing Theme', 'Generous Bonuses (TBD)'],
    cons: ['New Casino - Details TBC'],
    games: ['Slots', 'Casual Games'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [{
        id: 'moozi-review-admin',
        author: 'Admin',
        rating: 4.2,
        comment: 'Welcome Moozi! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Farmyard Fun Fest", "Cow Cash Cow-llector"],
    dailyMinSc: 1,
    dailyMaxSc: 1
  },
  {
    id: 'rollingriches',
    name: 'Rollingriches',
    slug: 'rollingriches',
    logoUrl: '/images/casinos/rollingriches.jpeg',
    tier: 'Solid',
    welcomeBonus: { amount: 'daily bonus', description: 'Details to be confirmed.' },
    features: ['Daily Rewards', 'Luxury Theme', 'High Roller (Social) Options'],
    pros: ['Premium Feel', 'Exclusive Games (TBD)'],
    cons: ['New Casino - Details TBC'],
    games: ['Slots', 'Table Games', 'Live Dealer (TBD)'],
    paymentMethods: ['Visa', 'Mastercard', 'Amex'],
    reviews: [{
        id: 'rollingriches-review-admin',
        author: 'Admin',
        rating: 4.5,
        comment: 'Welcome Rollingriches! More details coming soon.',
        date: '2024-07-26',
    }],
    bestGames: ["Velvet Rope VIP Slots", "Diamond Drive Deluxe"],
    dailyMinSc: 0.2,
    dailyMaxSc: 0.2
  },
  {
    id: 'chumbacasino',
    name: 'Chumbacasino',
    slug: 'chumbacasino',
    logoUrl: '/images/casinos/chumbacasino.jpeg',
    tier: 'Great',
    welcomeBonus: {
      amount: '0.3 SC Daily',
      description: 'Juicy welcome offers, free SC link drops daily, easy $1-2/day giveaways',
    },
    features: ['Daily Rewards', 'VIP Program', 'Cash Redemption', 'Gift Card Redemption'],
    pros: ['Great welcome offers', 'Daily free SC links', 'Easy earnings', 'Fast redemptions', 'Well Established'],
    cons: ['No crypto redemption'],
    games: ['Slots', 'Table Games', 'Live Dealer', 'Jackpot Slots'],
    paymentMethods: ['Cash', 'Gift Cards'],
    reviews: [
      {
        id: '16',
        author: 'Admin',
        rating: 5,
        comment: "Don't skip Chumba",
        date: '2024-03-15',
      },
    ],
    bestGames: [
      "Live Blackjack",
      "Live Roulette",
      "Live Bacarrat",
    ],
    dailyMinSc: 0.25,
    dailyMaxSc: 3
  },
  {
    id: 'luckylandslots',
    name: 'Luckyland Slots',
    slug: 'luckylandslots',
    logoUrl: '/images/casinos/luckyland.jpg',
    tier: 'Great',
    welcomeBonus: { amount: 'TBD', description: 'Details TBD' },
    features: ['Slots', 'Progressive Jackpots'],
    pros: ['Unique Games'],
    cons: ['Limited Info'],
    games: ['Slots'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [],
    bestGames: [
      "Galactic Blast - Progressive Jackpot",
      "Forbidden Fortunes - 243 Ways to Win",
      "Clover Cash - Lucky Charms, Bonus Game",
      "Amazonia - 3D Slot Adventure",
    ],
    dailyMinSc: 0.25,
    dailyMaxSc: 1
  },
  {
    id: 'luckyhands',
    name: 'Luckyhands Slots',
    slug: 'luckyhands',
    logoUrl: '/images/casinos/luckyhand.jpg',
    tier: 'Great',
    welcomeBonus: { amount: 'TBD', description: 'Details TBD' },
    features: ['Slots', 'Progressive Jackpots'],
    pros: ['Unique Games'],
    cons: ['Limited Info'],
    games: ['Slots'],
    paymentMethods: ['Visa', 'Mastercard'],
    reviews: [],
    bestGames: [
      "Galactic Blast - Progressive Jackpot",
      "Forbidden Fortunes - 243 Ways to Win",
      "Clover Cash - Lucky Charms, Bonus Game",
      "Amazonia - 3D Slot Adventure",
    ],
    dailyMinSc: 0.3,
    dailyMaxSc: 0.3
  }
]; 