-- AlterTable
ALTER TABLE "SavedCasino" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "dailyScValue" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "depositTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
